syntax on
":cd C:\Users\lanastasov\Desktop\clojure\clojure
:cd C:\Users\lanastasov\
set autochdir

set cindent
set tabstop=4
set shiftwidth=4
set visualbell t_vb=
set backspace=indent,eol,start
set fileencodings=utf-8

"set showmatch
"set incsearch
map <F2> :mksession! ~/vim_session <cr> " Quick write session with F2
map <F3> :source ~/vim_session <cr>		" And load session with F3
map <C-t> :tabnew <CR>
map <C-q> :q! <CR>
map <C-s> :w <CR>
nmap ,t <esc>:tabnew <CR>
imap <C-s> <esc>:w <CR>a
imap jk <Esc>			
"pathogen vim runs others scripts
call pathogen#infect()
filetype plugin indent on	

"VIM-RUBY
set nocompatible 
filetype on
filetype indent on
filetype plugin on
compiler ruby

"autocmd FileType html,xml,xsl source ~/vimfiles/scripts/closetag.vim
"autocmd FileType html,xml,xsl source ~\vimfiles\scripts\closetag.vim
let g:ragtag_global_maps = 1
"let g:clj_paren_rainbow=1
let vimclojure#ParenRainbow = 1
let vimclojure#HighlightBuiltins = 1
"map <F8> :w <CR> :!opa % <CR>a

autocmd FileType cpp set sw=4
autocmd FileType cpp set tabstop=4

"autocmd FileType opa map <F8> :w <CR> :!opa % <CR>

"autocmd FileType rb map <F8> :w <CR> :!ruby % <CR>
"autocmd FileType rb imap <F8> <Esc> :w <CR> :!ruby % <CR>

map <F8> :w <CR> :!ruby % <CR>
imap <F8> <Esc> :w <CR> :!ruby % <CR>

autocmd FileType ruby set sw=2
autocmd FileType ruby set tabstop=2

autocmd FileType java map <F8> :w <CR> :!java % <CR>
if has("autocmd")
    autocmd bufwritepost _vimrc source $MYVIMRC
endif

let mapleader = ","
nmap <leader>v :tabedit $MYVIMRC<CR>

set guifont=Consolas:h12:cANSI
